using System;

namespace TgrDevelopments.Cst.Packs.Perl;

enum PerlTokenKind
{
    None = 0,
    Identifier = 1,
    Number = 2,
    StringLiteral = 3,
    BacktickString = 4,
    SigilScalar = 5,
    SigilArray = 6,
    SigilHash = 7,
    SigilSub = 8,
    SigilGlob = 9,
    Arrow = 10,
    FatComma = 11,
    Assign = 12,
    Dot = 13,
    Comma = 14,
    Semicolon = 15,
    LParen = 16,
    RParen = 17,
    LBrace = 18,
    RBrace = 19,
    LBracket = 20,
    RBracket = 21,
    Colon = 22,
    Plus = 23,
    Minus = 24,
    Star = 25,
    Slash = 26,
    KeywordSub = 27,
    KeywordPackage = 28,
    KeywordMy = 29,
    KeywordOur = 30,
    KeywordLocal = 31,
    KeywordUse = 32,
    KeywordRequire = 33,
    KeywordIf = 34,
    KeywordUnless = 35,
    KeywordElse = 36,
    KeywordElsif = 37,
    KeywordWhile = 38,
    KeywordFor = 39,
    KeywordForeach = 40,
    KeywordDo = 41,
    KeywordEval = 42,
    KeywordBegin = 43,
    KeywordEnd = 44,
    KeywordReturn = 45,
    KeywordLast = 46,
    KeywordNext = 47,
    MatchBind = 48,
    NotMatchBind = 49,
    RegexLiteral = 50,
    Eof = -1,
}
