<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
    <ProjectReference Include="..\TgrDevelopments.Cst.Packs.Markdown\TgrDevelopments.Cst.Packs.Markdown.csproj" />
    <ProjectReference Include="..\TgrDevelopments.Cst\TgrDevelopments.Cst.csproj" />
    <ProjectReference Include="../TgrDevelopments.Cst.TestHelpers/TgrDevelopments.Cst.TestHelpers.csproj" />
  </ItemGroup>

</Project>
