<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
    <ProjectReference Include="..\TgrDevelopments.Cst.Packs.Csv\TgrDevelopments.Cst.Packs.Csv.csproj" />
    <ProjectReference Include="..\TgrDevelopments.Cst\TgrDevelopments.Cst.csproj" />
    <ProjectReference Include="..\TgrDevelopments.Cst.TestHelpers\TgrDevelopments.Cst.TestHelpers.csproj" />
  </ItemGroup>

</Project>
