namespace TgrDevelopments.Cst.Packs.TypeScript;

/// <summary>TypeScript token kinds for the hand-written lexer.</summary>
internal enum TsTokenKind
{
    Eof = -1,
    Identifier = 1,
    NumericLiteral,
    StringLiteral,
    TemplateLiteral,
    RegexLiteral,

    // keywords (subset used for structure)
    KwFunction,
    KwClass,
    KwAsync,
    KwStatic,
    KwGet,
    KwSet,
    KwConstructor,
    KwExtends,
    KwExport,
    KwDefault,
    KwImport,
    KwFrom,
    KwConst,
    KwLet,
    KwVar,
    KwReturn,
    KwIf,
    KwElse,
    KwFor,
    KwWhile,
    KwDo,
    KwSwitch,
    KwCase,
    KwBreak,
    KwContinue,
    KwTry,
    KwCatch,
    KwFinally,
    KwThrow,
    KwNew,
    KwThis,
    KwSuper,
    KwTypeof,
    KwInstanceof,
    KwVoid,
    KwDelete,
    KwIn,
    KwOf,
    KwYield,
    KwAwait,
    KwWith,
    KwDebugger,
    KwTrue,
    KwFalse,
    KwNull,
    KwUndefined,
    KwInterface,
    KwType,
    KwEnum,
    KwNamespace,
    KwModule,
    KwImplements,
    KwDeclare,
    KwAbstract,
    KwReadonly,
    KwPublic,
    KwPrivate,
    KwProtected,
    KwOverride,

    // punctuation
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Semicolon,
    Comma,
    Dot,
    Question,
    Colon,
    Arrow,       // =>
    Ellipsis,    // ...
    Eq,          // =
    EqEq,
    EqEqEq,
    Bang,
    BangEq,
    BangEqEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    Plus,
    Minus,
    Star,
    StarStar,
    Slash,
    Percent,
    Amp,
    AmpAmp,
    Pipe,
    PipePipe,
    Caret,
    Tilde,
    PlusPlus,
    MinusMinus,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    LtLt,
    GtGt,
    GtGtGt,
    QuestionQuestion,
    QuestionDot,

    Other, // unknown single char / operator fallback
}
